# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/satya/Repos/ASE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/satya/Repos/ASE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/satya/Repos/ASE/CMakeFiles /home/satya/Repos/ASE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/satya/Repos/ASE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Main

# Build rule for target.
Main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Main
.PHONY : Main

# fast build rule for target.
Main/fast:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/build
.PHONY : Main/fast

Bind/bind.o: Bind/bind.c.o

.PHONY : Bind/bind.o

# target to build an object file
Bind/bind.c.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Bind/bind.c.o
.PHONY : Bind/bind.c.o

Bind/bind.i: Bind/bind.c.i

.PHONY : Bind/bind.i

# target to preprocess a source file
Bind/bind.c.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Bind/bind.c.i
.PHONY : Bind/bind.c.i

Bind/bind.s: Bind/bind.c.s

.PHONY : Bind/bind.s

# target to generate assembly for a file
Bind/bind.c.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Bind/bind.c.s
.PHONY : Bind/bind.c.s

Display/display.o: Display/display.c.o

.PHONY : Display/display.o

# target to build an object file
Display/display.c.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Display/display.c.o
.PHONY : Display/display.c.o

Display/display.i: Display/display.c.i

.PHONY : Display/display.i

# target to preprocess a source file
Display/display.c.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Display/display.c.i
.PHONY : Display/display.c.i

Display/display.s: Display/display.c.s

.PHONY : Display/display.s

# target to generate assembly for a file
Display/display.c.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Display/display.c.s
.PHONY : Display/display.c.s

Flags/flags.o: Flags/flags.c.o

.PHONY : Flags/flags.o

# target to build an object file
Flags/flags.c.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Flags/flags.c.o
.PHONY : Flags/flags.c.o

Flags/flags.i: Flags/flags.c.i

.PHONY : Flags/flags.i

# target to preprocess a source file
Flags/flags.c.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Flags/flags.c.i
.PHONY : Flags/flags.c.i

Flags/flags.s: Flags/flags.c.s

.PHONY : Flags/flags.s

# target to generate assembly for a file
Flags/flags.c.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Flags/flags.c.s
.PHONY : Flags/flags.c.s

Glob/glob.o: Glob/glob.c.o

.PHONY : Glob/glob.o

# target to build an object file
Glob/glob.c.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Glob/glob.c.o
.PHONY : Glob/glob.c.o

Glob/glob.i: Glob/glob.c.i

.PHONY : Glob/glob.i

# target to preprocess a source file
Glob/glob.c.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Glob/glob.c.i
.PHONY : Glob/glob.c.i

Glob/glob.s: Glob/glob.c.s

.PHONY : Glob/glob.s

# target to generate assembly for a file
Glob/glob.c.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Glob/glob.c.s
.PHONY : Glob/glob.c.s

Math/mathop.o: Math/mathop.c.o

.PHONY : Math/mathop.o

# target to build an object file
Math/mathop.c.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Math/mathop.c.o
.PHONY : Math/mathop.c.o

Math/mathop.i: Math/mathop.c.i

.PHONY : Math/mathop.i

# target to preprocess a source file
Math/mathop.c.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Math/mathop.c.i
.PHONY : Math/mathop.c.i

Math/mathop.s: Math/mathop.c.s

.PHONY : Math/mathop.s

# target to generate assembly for a file
Math/mathop.c.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Math/mathop.c.s
.PHONY : Math/mathop.c.s

Memory/mem.o: Memory/mem.c.o

.PHONY : Memory/mem.o

# target to build an object file
Memory/mem.c.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Memory/mem.c.o
.PHONY : Memory/mem.c.o

Memory/mem.i: Memory/mem.c.i

.PHONY : Memory/mem.i

# target to preprocess a source file
Memory/mem.c.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Memory/mem.c.i
.PHONY : Memory/mem.c.i

Memory/mem.s: Memory/mem.c.s

.PHONY : Memory/mem.s

# target to generate assembly for a file
Memory/mem.c.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Memory/mem.c.s
.PHONY : Memory/mem.c.s

Parser/parse.o: Parser/parse.c.o

.PHONY : Parser/parse.o

# target to build an object file
Parser/parse.c.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Parser/parse.c.o
.PHONY : Parser/parse.c.o

Parser/parse.i: Parser/parse.c.i

.PHONY : Parser/parse.i

# target to preprocess a source file
Parser/parse.c.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Parser/parse.c.i
.PHONY : Parser/parse.c.i

Parser/parse.s: Parser/parse.c.s

.PHONY : Parser/parse.s

# target to generate assembly for a file
Parser/parse.c.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Parser/parse.c.s
.PHONY : Parser/parse.c.s

Stack/stack.o: Stack/stack.c.o

.PHONY : Stack/stack.o

# target to build an object file
Stack/stack.c.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Stack/stack.c.o
.PHONY : Stack/stack.c.o

Stack/stack.i: Stack/stack.c.i

.PHONY : Stack/stack.i

# target to preprocess a source file
Stack/stack.c.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Stack/stack.c.i
.PHONY : Stack/stack.c.i

Stack/stack.s: Stack/stack.c.s

.PHONY : Stack/stack.s

# target to generate assembly for a file
Stack/stack.c.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Stack/stack.c.s
.PHONY : Stack/stack.c.s

TEngine/tengine.o: TEngine/tengine.c.o

.PHONY : TEngine/tengine.o

# target to build an object file
TEngine/tengine.c.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/TEngine/tengine.c.o
.PHONY : TEngine/tengine.c.o

TEngine/tengine.i: TEngine/tengine.c.i

.PHONY : TEngine/tengine.i

# target to preprocess a source file
TEngine/tengine.c.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/TEngine/tengine.c.i
.PHONY : TEngine/tengine.c.i

TEngine/tengine.s: TEngine/tengine.c.s

.PHONY : TEngine/tengine.s

# target to generate assembly for a file
TEngine/tengine.c.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/TEngine/tengine.c.s
.PHONY : TEngine/tengine.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Main"
	@echo "... edit_cache"
	@echo "... Bind/bind.o"
	@echo "... Bind/bind.i"
	@echo "... Bind/bind.s"
	@echo "... Display/display.o"
	@echo "... Display/display.i"
	@echo "... Display/display.s"
	@echo "... Flags/flags.o"
	@echo "... Flags/flags.i"
	@echo "... Flags/flags.s"
	@echo "... Glob/glob.o"
	@echo "... Glob/glob.i"
	@echo "... Glob/glob.s"
	@echo "... Math/mathop.o"
	@echo "... Math/mathop.i"
	@echo "... Math/mathop.s"
	@echo "... Memory/mem.o"
	@echo "... Memory/mem.i"
	@echo "... Memory/mem.s"
	@echo "... Parser/parse.o"
	@echo "... Parser/parse.i"
	@echo "... Parser/parse.s"
	@echo "... Stack/stack.o"
	@echo "... Stack/stack.i"
	@echo "... Stack/stack.s"
	@echo "... TEngine/tengine.o"
	@echo "... TEngine/tengine.i"
	@echo "... TEngine/tengine.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

